### ISSUE TITLE
auto accept next quest

### ISSUE THREAD

**Issue by Sigma88** [seblindfors/Immersion#5]
when I turn in a quest I can't read the final text because the next quest is automatically accepted and the text for that quest replaces the old text immediately.

is there a way to avoid this?

thanks for the help! 👍

**Comment by seblindfors** [comment]
Immersion does not automatically turn in/accept quests. It's possible you have another addon doing this for you. The typical turn in gives you a dialogue where the quest giver says something like "got my boar ears?" and then you progress to completion, where you see your rewards. After turning that in, you might get directed into a follow up quest if the NPC has one. If you're not seeing this, I think it might be due to other addons.

**Comment by Sigma88** [comment]
sorry forgot to update and close this issue.

I found out later that all quests in the starting zone are automatically accepted (default blizz behaviour)

I just ignored it in the beginning and read the text from the quest log.

it doesn't bother me anymore so I close this issue now, but it might be a good idea to look into it if it's possible to block the behaviour in case other players experience the same issues I had.

and thanks for the reply!
